# Generated by Django 2.0.3 on 2018-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0010_auto_20180215_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['client', 'performer', '-created'], 'verbose_name': 'Relationship', 'verbose_name_plural': 'My Relationships'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='label',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
