# Generated by Django 2.0.3 on 2018-03-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0011_auto_20180310_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
