# Generated by Django 2.0.3 on 2018-03-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0012_profile_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Default_profile_picture_%28male%29_on_Facebook.jpg/600px-Default_profile_picture_%28male%29_on_Facebook.jpg'),
        ),
    ]
