# Generated by Django 2.0.3 on 2018-03-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0013_auto_20180317_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
