# Generated by Django 2.0.3 on 2018-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0013_auto_20180317_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='isReadTutorial',
            field=models.BooleanField(default=False),
        ),
    ]
