# Generated by Django 2.0.3 on 2018-03-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0014_auto_20180317_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['client', 'performer', '-created']},
        ),
    ]
