# Generated by Django 2.0 on 2018-02-21 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='文章')),
                ('category', models.SmallIntegerField(choices=[(1, '故事'), (2, '課程'), (3, '學習資源')], default=1)),
                ('content', models.TextField(blank=True, default='文章')),
                ('img', models.URLField(default='https://i.imgur.com/67A5cyq.jpg')),
                ('url', models.URLField(default='https://i.imgur.com/67A5cyq.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='最新消息')),
                ('url', models.URLField(default='https://i.imgur.com/67A5cyq.jpg')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
