# Generated by Django 2.0 on 2018-02-24 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.TextField(blank=True, default='文章'),
        ),
    ]
