# Generated by Django 2.0 on 2018-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0006_auto_20180224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.SlugField(),
        ),
    ]
