# Generated by Django 2.0 on 2018-02-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0007_auto_20180224_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='label',
        ),
    ]
