# Generated by Django 2.0 on 2018-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0008_remove_news_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
    ]
