# Generated by Django 2.0 on 2018-02-24 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0009_auto_20180224_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='label',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default='最新消息'),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default='https://i.imgur.com/67A5cyq.jpg'),
        ),
    ]
