# Generated by Django 2.0 on 2018-03-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0011_merge_20180303_0734'),
        ('sky', '0011_merge_20180303_0733'),
    ]

    operations = [
    ]
