# Generated by Django 2.0 on 2018-03-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_auto_20180307_0537'),
        ('sky', '0012_merge_20180306_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Task'),
        ),
    ]
