# Generated by Django 2.0 on 2018-03-07 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0013_article_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Task'),
        ),
    ]
