# Generated by Django 2.0.3 on 2018-03-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_auto_20180307_0537'),
        ('sky', '0014_auto_20180307_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Task'),
        ),
    ]
