# Generated by Django 2.0.3 on 2018-03-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0015_course_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['category', '-title', '-created'], 'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-teacher', '-created'], 'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created', 'title'], 'verbose_name': 'News'},
        ),
        migrations.AlterField(
            model_name='article',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Task'),
        ),
        migrations.AlterField(
            model_name='course',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Task'),
        ),
    ]
