# Generated by Django 2.0.3 on 2018-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0006_auto_20180220_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingvocher',
            options={'ordering': ['user', 'vocher', 'be_used', '-created']},
        ),
        migrations.AddField(
            model_name='vocher',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '無限制'), (2, '每週限制'), (3, '總數限制')], default=1),
        ),
        migrations.AddField(
            model_name='vocher',
            name='limit',
            field=models.IntegerField(blank=True, default=0, help_text="Only required if 'category' is 每週限制 or 總數限制."),
        ),
        migrations.AlterField(
            model_name='holdingvocher',
            name='label',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
