# Generated by Django 2.0.3 on 2018-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0009_store_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocher',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
