# Generated by Django 2.0 on 2018-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_auto_20180224_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='課程名稱')),
                ('teacher', models.TextField(default='教師名稱')),
                ('more', models.TextField(default='教師名稱')),
                ('img', models.URLField(default='https://i.imgur.com/67A5cyq.jpg')),
                ('content', models.TextField(blank=True, default='內文')),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
    ]
