# Generated by Django 2.0 on 2018-03-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_auto_20180303_0053'),
        ('sky', '0010_auto_20180224_1143'),
    ]

    operations = [
    ]
