# Generated by Django 2.0 on 2018-03-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20180125_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstask',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
