# Generated by Django 2.0 on 2018-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_remove_progresstask_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstask',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
