# Generated by Django 2.0 on 2018-03-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_progresstask_is_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstask',
            name='is_finish',
        ),
    ]
