# Generated by Django 2.0 on 2018-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_remove_progresstask_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '每日任務'), (2, '限時任務'), (3, '彩蛋'), (4, '閱讀文章')], default=1),
        ),
    ]
