# Generated by Django 2.0.3 on 2018-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_auto_20180307_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresstask',
            options={'ordering': ['user', 'task', '-last_active_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['category', 'due_date', '-credit']},
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
