# Generated by Django 2.0.3 on 2018-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20180310_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '每日任務'), (2, '限時任務'), (3, '彩蛋')], default=1),
        ),
    ]
