# Generated by Django 2.0.3 on 2018-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_auto_20180312_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='credit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
